name: lookalittlecloser
favicon: null
layout_spectrum: 0.91374
typography_spectrum: 0.93726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e5f0f5'
    - '#006730'
    - '#95000a'
    - '#d05794'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
