name: lookalittlecloser
favicon: null
layout_spectrum: 0.14992
typography_spectrum: 0.93726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f4f2'
    - '#151517'
    - '#fe9a5d'
    - '#009c65'
    - '#be6660'
  brandStrength: 0.625
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
