name: lookalittlecloser
favicon: null
layout_spectrum: 0.5830557884182781
typography_spectrum: 0.93726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f5f8'
    - '#9c96a4'
    - '#8a754c'
    - '#170c1f'
    - '#1991a1'
  brandStrength: 0.125
  lightness: 0.6963115395046771
  saturation: 0.1875
  rhythmicContrast: 0.5392585219815373
purpose: []
